services:
  app:
    build:
      target: prerelease # Use the stage with dev dependencies
    command: bun --watch run src/main.ts # Override for hot-reloading
    volumes:
      - ./src:/usr/src/app/src # Mount local src into the container
    env_file:
      - .env.local
      - .env.development
  db:
    env_file:
      - .env.local
      - .env.development
